Main/django_blog/blog_app/urls.py
from django.conf.urls import url
from blog_app import views
#from blog_app.views import AddPostView
from blog_app.views import  ArticleDetailView
app_name = 'blog_app'

urlpatterns = [
    
    url(r'^register/$', views.register, name="registration"),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^addpost/$', views.addpost, name="addpost"),
    url(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetailView.as_view(), name="article"),
    url(r'^editpost/(?P<id>[0-9]+)/$', views.editpost, name="editpost"),
    url(r'^deletepost/(?P<id>[0-9]+)/$', views.deletepost, name="deletepost"),
    url(r'^editprofile/$', views.editprofile, name="editprofile"),
    url(r'^searchpost/$', views.searchpost, name="searchblog"),

]

Main/django_blog/django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog_app/', include('blog_app.urls')),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^user_profile/$', views.user_profile, name="user_profile"),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/django_blog/blog_app/models.py
from ast import arg
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from PIL import Image
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
# Create your models here.

STATUS = (

    (0, 'Draft'),

    (1, 'Published')

)

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField( max_length=50)

    last_name = models.CharField( max_length=50)
    
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    
    
    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('editprofile', args=(str(self.id)))


class Post(models.Model):
    
    author = models.ForeignKey(User, editable=False, on_delete= models.CASCADE,related_name='blog_posts', null=True)

    title = models.CharField(max_length=200)

    content = models.TextField()

    status = models.IntegerField(choices=STATUS, default=0)

    blog_pic = models.ImageField(upload_to="blog_pics", blank=True, null=True)

    created_on = models.DateTimeField(auto_now_add=True)



    def __str__(self):

        return self.title

    def get_absolute_url(self):
        return reverse('article', args=(str(self.id)))

Main/django_blog/blog_app/forms.py
from django import forms
from django.contrib.auth.models import User
from blog_app.models import UserProfileInfo, Post



class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UpdateUserForm(forms.ModelForm): 
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ['profile_pic']


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        exclude = ['author']
        fields = ['title',  'content', 'status',  'blog_pic']

Main/django_blog/blog_app/views.py
from django.shortcuts import render, redirect
from blog_app.forms import UserForm, UserProfileInfoForm, PostForm, UpdateUserForm
from blog_app.models import Post,UserProfileInfo
from django.views.generic import  DetailView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from blog_app.models import Post
from django.core.files.storage import FileSystemStorage
from django.db.models import Q


# Create your views here.

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'blog_app/article.html'
    

# class AddPostView(CreateView):
#     model =Post
#     # model1 = UserForm

#     # user1= UserForm.username

#     template_name = 'blog_app/addpost.html'
#     fields = ['title',  'content', 'status']

def addpost(request):

    if request.method == 'POST':
        post_form = PostForm(data=request.POST, files=request.FILES)

        if post_form.is_valid():
            blogpost = post_form.save(commit=False)
            blogpost.author = request.user
            blogpost.save()
            return redirect( 'user_profile')
    
        # else:
        #     print(post_form.error)
    else:
        post_form = PostForm()

    return render (request, 'blog_app/addpost.html', {'post_form':post_form,})

#function to delete 
def deletepost(request,id):
    posts = Post.objects.get(id=id)
    if request.method == "POST":
        posts.delete()
        return redirect('user_profile')
    return render (request, 'blog_app/deletepost.html', {'post':posts})


#function to edit
def editpost(request, id):
    post = Post.objects.get(id=id)
    blog=PostForm(instance=post)
    if request.method=="POST":
        post_form = PostForm(request.POST, request.FILES, instance=post)
        if post_form.is_valid():
            post_form.save()
            return redirect( 'user_profile')
    return render(request, "blog_app/editpost.html", {'blog':post,})
#for search 
def searchpost(request):
    if request.method == "POST":
        searched = request.POST['searched']
        blogs = Post.objects.filter(Q(title__contains=searched) | Q(content__contains=searched))
        post_dict = {'post_list': blogs}

        return render(request, 'blog_app/user_profile.html', post_dict, {'searched':searched, 'blogs':blogs})
    else:
        return render(request, "blog_app/user_profile.html", {})

#function to edit profile
def editprofile(request):
    user = request.user
    userpro =UpdateUserForm(instance=user)
    profile_form = UserProfileInfoForm(instance=request.user.userprofileinfo)

    if request.method=="POST":
        user_form = UpdateUserForm(data=request.POST, instance=request.user)
        profile_form = UserProfileInfoForm(request.POST, request.FILES, instance=request.user.userprofileinfo)

        if user_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect( 'user_profile')
    return render(request, "blog_app/editprofile.html", {'user_form':userpro, 'profile_form': profile_form})


def index(request):
     return render(request, 'blog_app/index.html')


@login_required
def user_profile(request):
    queryset = Post.objects.filter(status=1)
    post_dict = {'post_list': queryset}
    return render(request, 'blog_app/user_profile.html', context=post_dict)



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # if 'profile_pic' in request.FILES:
            #     profile.profile_pic = request.FILES['profile_pic']

            # profile.save()
            image = request.FILES['profile_pic']
            if image:
                filename = FileSystemStorage().save('profile_pics/' + image.name, image)
                profile.profile_pic = filename
            profile.save()
            
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'blog_app/registration.html', 
                  {'user_form':user_form,
                  'profile_form':profile_form,
                  'registered':registered
                  })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse(user_profile))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details!")

    else:
        return render(request, 'blog_app/login.html')

Main/django_blog/templates/blog_app/addpost.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}

{% load staticfiles %}

{% block content %}

<div class="login-form login blog-post">
    <header class=" login--header register--header text-center">
        <img src="{{ user.userprofileinfo.profile_pic.url }}" width="80" height="80" class="rounded-circle">
        <h3 >Author: {{ user.first_name }} {{ user.last_name }}</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
    <form action="{% url 'blog_app:addpost'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Title" name="title">
            </div>
        </div>

        <div class="form-group text-left"> 
            <label>Content:</label>
            <textarea class="form-control" id="content" name="content" rows="5"></textarea>
        </div>
        
        <div class="row form-check d-flex ">
            <div class="form-group">
                <label for="id_status">Status:</label>
            </div>
        
            <div class="col-xs-6 col-sm-6 col-md-6">
               <div >
                 <select class="form-control" name="status" id="id_status" >
                     <option value="0" selected>Draft</option>
                     <option value="1">Published</option>
                 </select>
               </div>
            </div>
        </div>
        <div class="row form-check d-flex ">
            <div class="form-group">
                <label class="form-check-label" style="margin-top:-2px" for="id_blog_pic">Post Picture:</label>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div >
                 <input type="file" name="blog_pic" id="id_blog_pic">
                </div>
            </div>
        </div>
        <div class="row" style="margin-top:20px;">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary btn-block">Post</button>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <a href='/user_profile' class="form-control btn btn-danger btn-block">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>



{% endblock %}

Main/django_blog/templates/blog_app/article.html
{% extends "blog_app/base.html" %}
{% block content %}
<div class="container mt-5 mb-3">
    <div class="row">
        <div class="card shadow " style="width: 30rem; height: 40rem;" >
        <img src="{{ post.blog_pic.url }}" class="card-img-top" alt="..." height="250px">
        <div class="card-body" style="overflow:hidden;">
            <h5 class="card-title">{{post.title}} <br><small>by {{post.author}}</small></h5>
            <p class="card-text">{{ post.content}}</p>
            
            <hr>
            </div>
            <a href="{% url 'user_profile' %}">Go Back to profile</a>
            <div class="card-footer" style="border-top:none">
                {% if post.author.id == request.user.id %}
              <div class="d-flex flex-row justify-content-end mt-auto">
                <a href="{% url 'blog_app:editpost' post.id %}" class="btn btn-primary d-flex justify-content-end">Edit Post <a href="{% url 'blog_app:deletepost' post.id %}" class="btn btn-danger mx-4">Delete</a></a>
                </div> 
              {% endif %}
                 {% if post.status == 0 %}
            <p class="card-text"><small class="text-muted">Draft on {{ post.created_on }}  </small></p>
            
            
            {% else %}
            <p class="card-text"><small class="text-muted">Published on {{ post.created_on }}  </small></p>
            
            {% endif %}
              </div>
        </div>
    </div>
</div>
{% endblock %}

Main/django_blog/templates/blog_app/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/basicstyle.css' %}">
    <link href="{% static 'styles/base.css' %}" rel="stylesheet">

    {% block styles %}{% endblock %}
</head>
<body>
<header>
  <nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/logo_white.png" width="30" height="30" alt="logo">
      Blog Project
    </a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_profile' %}">Hi {{ user.username }}!</a>
      </li>
     
    </ul>
¨
    <div class="collapse navbar-collapse justify-content-end" id="navbar-list-4">
      <form class="collapse navbar-collapse justify-content-end" action="{% url 'blog_app:searchblog'  %}" method="POST">
        {% csrf_token %}
      <div class="input-group rounded" style="width:30%; height:70%">
        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" id="searched" name="searched"/>
        <button class="input-group-text border-0" id="search-addon">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </form>
      <ul class="navbar-nav ">
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{{ user.userprofileinfo.profile_pic.url }}" width="40" height="40" class="rounded-circle">
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'blog_app:editprofile' %}">Edit Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
          </div>
        </li>   
      </ul>
    </div>
    {% endif %}
  </nav>
  </header>

<div id="content-wrap">
{% block content %}

{% endblock %}

</div>

<div class="container" >
  <footer class="py-0  footer fixed-bottom bg-dark " id="footer">
    
    <p class="text-center " style="color: white;">© 2022 Blog Project</p>
  </footer>
</div>

</body>
</html>

Main/django_blog/templates/blog_app/deletepost.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}

{% load staticfiles %}

{% block content %}

<div class="login-form login blog-post">
    <header class=" login--header register--header text-center">
        <img src="{{ post.blog_pic.url }}" width="80" height="80" class="rounded-circle">
        <h3 >Auther: {{ user.first_name }} {{ user.last_name }}</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
  <form action="{% url 'blog_app:deletepost' post.id %}" method="POST">
    {% csrf_token %}

    <div class="form-group text-left">
        <label>Title:</label>
        <input type="text" class="form-control" placeholder="Title" name="title" value="{{ post.title }}">
    </div>

    <div class="form-group text-left"> 
        <label>Content:</label>
        <p class="form-control card-text">{{ post.content | truncatechars:50}}</p>
    </div>
    
    <div class="row form-check d-flex ">
        <div class="form-group">
            <label for="id_status">Status:</label>
        </div>
    
        <div class="col-xs-6 col-sm-6 col-md-6">
           <div >
             <select class="form-control" name="status" id="id_status" disabled >
                 <option value="0" {% if post.status == 0 %}selected{% endif %}>Draft</option>
                 <option value="1" {% if post.status == 1 %}selected{% endif %}>Published</option>
             </select>
           </div>
        </div>
    </div>
    <div class="row" style="margin-top:20px;">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <button type="submit" class="form-control btn btn-primary btn-block">Delete</button>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <a href='/user_profile' class="form-control btn btn-danger btn-block">Cancel</a>
            </div>
        </div>
    </div>
</form>
</div>

{% endblock %}

Main/django_blog/templates/blog_app/editpost.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}

{% load staticfiles %}

{% block content %}

<div class="login-form login blog-post">
    <header class=" login--header register--header text-center">
        <img src="{{ blog.blog_pic.url }}" width="80" height="80" class="rounded-circle">
        <h3 >Auther: {{ user.first_name }} {{ user.last_name }}</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
    <form action="{% url 'blog_app:editpost' blog.id%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Title" name="title" value="{{ blog.title }}">
            </div>
        </div>

        <div class="form-group text-left"> 
            <label>Content:</label>
            <textarea class="form-control" id="content" name="content" rows="5"> {{ blog.content }}</textarea>
        </div>
        
        <div class="row form-check d-flex ">
            <div class="form-group">
                <label for="id_status">Status:</label>
            </div>
        
            <div class="col-xs-6 col-sm-6 col-md-6">
               <div >
                 <select class="form-control" name="status" id="id_status" >
                     <option value="0" {% if blog.status == 0 %}selected{% endif %}>Draft</option>
                     <option value="1" {% if blog.status == 1 %}selected{% endif %}>Published</option>
                 </select>
               </div>
            </div>
        </div>
        <div class="row form-check d-flex ">
            <div class="form-group">
                <label class="form-check-label" style="margin-top:-2px" >Post Picture:</label>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div >
                 <input type="file" name="blog_pic" id="id_blog_pic" value="{{ blog.blog_pic }}">
                </div>
            </div>
        </div>
        <div class="row" style="margin-top:20px;">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary btn-block">Update</button>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <a href='/user_profile' class="form-control btn btn-danger btn-block">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>




{% endblock %}

Main/django_blog/templates/blog_app/editprofile.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}

{% load staticfiles %}

{% block content %}
<div class="login-form login ">
    <header class=" login--header  text-center">
        <img src="{{ user.userprofileinfo.profile_pic.url }}" width="80" height="80" class="rounded-circle">
        <h3>Update</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
    <form action="{% url 'blog_app:editprofile'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name" value="{{ user.first_name }}">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name" value="{{ user.last_name }}">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="username" id="username" class="form-control input-sm" placeholder="User Name" value="{{ user.username }}">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password" value="{{ user.password }}">
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="input-group">
                <input type="email" class="form-control" placeholder="E-mail" required="required" name="email" value="{{ user.email }}">
            </div>
        </div>
        
        <div class="row form-check d-flex">
                <div class="form-group">
                    <label class="form-check-label" style="margin-top:-2px" for="id_profile_pic">Profile Picture:</a>
                    </label>
                </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="file" name="profile_pic" id="id_profile_pic" value="{{ user.userprofileinfo.profile_pic.url }}">
                </div>
            </div>
        </div>
       
        <div class="form-check d-flex" style="margin-top:10px; text-align: left;">
            <input class="form-check-input me-2" type="checkbox" />
            <label class="form-check-label" style="margin-top:-2px">
                I agree all statements in <a href="#!">Terms of service</a>
            </label>
        </div>
        <div class="row" style="margin-top:20px;">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary btn-block">Update</button>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <a href='/user_profile' class="form-control btn btn-danger btn-block">Cancel</a>
                </div>
            </div>

        </div>
    </div>
    </form>
</div>


{% endblock %}

Main/django_blog/templates/blog_app/index.html
{% extends "blog_app/base.html" %}

{% load staticfiles %}


{% load static %}
{% block title %}Blogged Project - Group 5{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h1>This is the worlds best blog!!!</h1>
<br>
<br>
<img class="rounded-circle article-img" src="{{ user.userprofileinfo.profile_pic.url }}" width='240' alt={{user}}><br>
<br>
<h3>Hi I'm {{ request.user.first_name }}</h3>



{% else %}
<div class="login-form login">
    <header class="login--header text-center">
        <span class="icon icon-medium fa fa-lock"></span>
        <h3>login</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
    <form action="{% url 'blog_app:user_login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
        	<div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <span class="fa fa-user"></span>
                    </span>                    
                </div>
                <input type="text" class="form-control" placeholder="Username" required="required" name="username">
            </div>
        </div>
		<div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="fa fa-lock"></i>
                    </span>                    
                </div>
                <input type="password" class="form-control" placeholder="Password" required="required" name="password">
            </div>
        </div>        
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <div class="bottom-action clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
            <a href="#" class="float-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center medium" >Don't have an account! <a href="{% url 'blog_app:registration' %}">Sign up here</a>.</p>
</div>

{% endif %}
{% endblock %}

Main/django_blog/templates/blog_app/registration.html
<!DOCTYPE html>
{% extends "blog_app/base.html" %}

{% load staticfiles %}

{% block content %}

{% if registered %}
    <h1>Thank you for Signing Up</h1>
        Do you want to log in? <a href="{% url 'blog_app:user_login' %}">Login</a>

{% else %}
<div class="login-form login">
    <header class=" login--header text-center">
        <span class="icon icon-medium fa fa-user"></span>
        <h3>Register</h3>
        <span class="arrow-down login--header__arrow"></span>
    </header>
    <form action="{% url 'blog_app:registration' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="text" name="username" id="username" class="form-control input-sm" placeholder="User Name">
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="input-group">
                <input type="email" class="form-control" placeholder="E-mail" name="email">
            </div>
        </div>
        
        <div class="row form-check d-flex">
                <div class="form-group">
                    <label class="form-check-label" style="margin-top:-2px" for="id_profile_pic">Profile Picture:</a>
                    </label>
                </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <input type="file" name="profile_pic" id="id_profile_pic">
                </div>
            </div>
        </div>
       
        <div class="form-check d-flex" style="margin-top:10px; text-align: left;">
            <input class="form-check-input me-2" type="checkbox" />
            <label class="form-check-label" style="margin-top:-2px">
                I agree all statements in <a href="#!">Terms of service</a>
            </label>
        </div>
        <div class="row" style="margin-top:20px;">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary btn-block">Register</button>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="form-group">
                    <a href="{% url 'blog_app:user_login' %}" class="form-control btn btn-danger btn-block">Cancel</a>
                </div>
            </div>

        </div>
    </form>
 {% endif %}
</div>

{% endblock %}

Main/django_blog/templates/blog_app/user_profile.html
{% extends "blog_app/base.html" %}



{% block content %}
<a class='btn btn-primary btn-rounded btn-icon pull-right btn-lg' href="{% url 'blog_app:addpost'%}"> <i class="fa fa-pencil-square-o  "></i> </a>    
<div class="container mt-5 mb-3">
  <div class="row">
    {% for post in post_list %}
    <div class="card shadow " style="width: 20rem; height: 30rem;" >
          <img src="{{ post.blog_pic.url }}" class="card-img-top" alt="..." height="250px">

          <div class="card-body" style="overflow:hidden;">
            <h5 class="card-title">{{post.title}} <br><small>by {{post.author}}</small></h5>
            <p class="card-text">{{ post.content | truncatechars:50}}</p>
            
          </div>
          <a href="{% url 'blog_app:article' post.id %}">Read More</a>

          <div class="card-footer" style="border-top:none">
            {% if post.author.id == request.user.id %}
          <div class="d-flex flex-row justify-content-end mt-auto">
            <a href="{% url 'blog_app:editpost' post.id %}" class="btn btn-primary d-flex justify-content-end">Edit Post <a href="{% url 'blog_app:deletepost' post.id %}" class="btn btn-danger mx-4">Delete</a></a>
            </div> 
          {% endif %}

          {% if post.status == 0 %}
            <p class="card-text"><small class="text-muted">Draft on {{ post.created_on }}  </small></p>
            
            
            {% else %}
            <p class="card-text"><small class="text-muted">Published on {{ post.created_on }}  </small></p>
            
            {% endif %}
          </div>

    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}